### ISSUE TITLE
Crash when copying from target executable path

### ISSUE THREAD

**Issue by SaculRennorb** [EpicGamesExt/raddebugger#580]
I had a second executable target set up for a while now, went back to it and wanted to copy paste the executable path into the working directory.  
When trying to do so, clicking into the executable path box i think it cleared itself.  
I then pressed ctrl+c to copy the value, and the debugger crashed. Here is the stacktrace and dump:

<img width="505" height="412" alt="Image" src="https://github.com/user-attachments/assets/713da5a7-48d2-4318-b709-3416cdcd579d" />

[raddbg_crash_dump.dmp](https://github.com/user-attachments/files/21552291/raddbg_crash_dump.dmp)

I would have copy pasted it, but it appears that while the dialog was still up it made my clipboard not work properly. Probably some windows because becasue it crashed in a clipboard handler.

**Comment by ryanfleury** [comment]
This was fixed in 7dca3fd954a9a76f5a62aa8bf38a43423304f88d, so if you pull and rebuild this should not happen again.

**Comment by SaculRennorb** [comment]
Nice! I was reporting it just in case, because I was sure it wouldn't reproduce since i've done the copy pasting loads of times without issue. 

Btw; I was only doing that copy pasting in the first place because i'm also encountering #555 where the working directory isn't saved between restarts. 

Still happens on the latest master commit right now.
